# Como ya sabes, a los gatos les gustan mucho las cajas. 
# El misterio del 'gato en una caja' no se ha resuelto del todo, pero existen diferentes hipótesis. 
# Algunos creen que es el escondite del depredador, otros piensan que es un lugar seguro para el gato.
#
# Por supuesto, el gato de nuestra tarea de hoy no es una excepción. Pero el problema es que, 
# si ejecutamos el código, veremos que la caja no se ajusta para nada al gato…😿
#
# Como puedes ver, el tamaño de la caja se establece mediante las variables 'anchura' y 'altura'.
# Cambia estas variables para que el gato se ajuste perfectamente a la caja.
#
# Los colores del gato y de la caja también se establecen mediante variables. 
# Cambia estas variables si te queda tiempo.


import turtle

t = turtle.Turtle()

# Estas variables contienen los parámetros de la caja, se pueden cambiar
anchura = 350 # Anchura de la caja
altura = 250 # Altura de la caja
caja = "brown" # Color de la caja

# Estos son los parámetros de la caja, no cambies el código
t.color(caja)
t.up()
t.goto(-150, -70)
t.down()

# La caja se dibuja aquí
t.forward(anchura)
t.left(90)
t.forward(altura)
t.left(90)
t.forward(anchura)
t.left(90)
t.forward(altura)
t.left(90)

# Estas variables contienen los colores del gato, puedes cambiarlos
gato = "orangered" # Color del pelaje del gato
ojos = "green" # Color de los ojos del gato
nariz = "pink" # Color de la nariz y las orejas del gato

# El siguiente código no debe cambiarse, el mismo dibuja un gato
t.speed(0)
t.color(gato)
t.up()
t.goto(0, 80)
t.down()
t.fill(1)
t.forward(50)
t.left(45)
t.forward(20)
t.left(45)
t.forward(30)
t.left(45)
t.forward(20)
t.left(45)
t.right(60)
t.forward(30)
t.left(120)
t.forward(30)
t.right(60)
t.forward(30)
t.right(60)
t.forward(30)
t.left(120)
t.forward(30)
t.right(15)
t.forward(20)
t.left(45)
t.forward(30)
t.left(45)
t.forward(20)
t.left(45)
t.forward(45)
t.fill(0)
t.color(nariz)
t.goto(5, 95)
t.right(90)
t.stamp()
t.up()
t.goto(-20, 115)
t.down()
t.color(ojos)
t.dot()
t.up()
t.goto(30, 115)
t.down()
t.dot()
t.color("pink")
t.left(180)
t.up()
t.goto(35, 150)
t.down()
t.stamp()
t.up()
t.goto(-25, 150)
t.down()
t.stamp()
t.color(gato)
t.up()
t.goto(5, 80)
t.down()
t.fill(1)
t.left(90)
t.forward(20)
t.left(45)
t.forward(30)
t.left(45)
t.forward(100)
t.left(45)
t.forward(10)
t.left(45)
t.forward(15)
t.left(45)
t.forward(10)
t.left(45)
t.forward(40)
t.right(45)
t.forward(5)
t.right(45)
t.forward(5)
t.right(45)
t.forward(5)
t.right(45)
t.forward(40)
t.left(45)
t.forward(10)
t.left(45)
t.forward(15)
t.left(45)
t.forward(10)
t.left(45)
t.forward(40)
t.right(45)
t.forward(5)
t.right(45)
t.forward(5)
t.right(45)
t.forward(5)
t.right(45)
t.forward(40)
t.left(45)
t.forward(10)
t.left(45)
t.forward(15)
t.left(45)
t.forward(10)
t.left(45)
t.forward(40)
t.right(45)
t.forward(5)
t.right(45)
t.forward(5)
t.right(45)
t.forward(5)
t.right(45)
t.forward(40)
t.left(45)
t.forward(10)
t.left(45)
t.forward(15)
t.left(45)
t.forward(10)
t.left(45)
t.forward(70)
t.right(45)
t.forward(60)
t.left(45)
t.forward(10)
t.left(45)
t.forward(10)
t.left(45)
t.forward(10)
t.left(45)
t.forward(50)
t.right(80)
t.forward(25)
t.left(35)
t.forward(45)
t.right(45)
t.forward(30)
t.fill(0)